import { Event } from "@/lib/types";
import { buildEventQrCode } from "@/lib/event-meta";

const RAW_MOCK_EVENTS: Event[] = [
  {
    id: "evt-1",
    organizerId: "organizer-demo",
    title: "Международная олимпиада по информатике",
    type: "olympiad",
    level: "international",
    dates: {
      start: "2026-04-20",
      end: "2026-04-24",
      registrationDeadline: "2026-04-10",
    },
    format: "offline",
    location: "Москва",
    description: "Международная олимпиада для студентов и школьников.",
    website: "https://example.org/ioi",
    contactEmail: "olympiad@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-1"),
    status: "published",
    participantsCount: 380,
    customFields: [],
    createdAt: "2026-02-10T09:00:00.000Z",
  },
  {
    id: "evt-2",
    organizerId: "organizer-demo",
    title: "Всероссийский хакатон по ИИ",
    type: "hackathon",
    level: "national",
    dates: {
      start: "2026-05-11",
      end: "2026-05-13",
      registrationDeadline: "2026-05-01",
    },
    format: "hybrid",
    location: "Санкт-Петербург",
    description: "Командный хакатон с задачами индустриальных партнеров.",
    website: "https://example.org/ai-hack",
    contactEmail: "hack@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-2"),
    status: "published",
    participantsCount: 260,
    customFields: [],
    createdAt: "2026-02-15T10:30:00.000Z",
  },
  {
    id: "evt-3",
    organizerId: "organizer-demo",
    title: "Региональная конференция молодых ученых",
    type: "conference",
    level: "regional",
    dates: {
      start: "2026-06-03",
      end: "2026-06-04",
      registrationDeadline: "2026-05-25",
    },
    format: "offline",
    location: "Казань",
    description: "Конференция с докладами и постерной сессией.",
    website: "https://example.org/science-conf",
    contactEmail: "conf@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-3"),
    status: "published",
    participantsCount: 145,
    customFields: [],
    createdAt: "2026-03-01T08:15:00.000Z",
  },
  {
    id: "evt-4",
    organizerId: "organizer-demo",
    title: "Университетская проектная школа",
    type: "course",
    level: "university",
    dates: {
      start: "2026-06-20",
      end: "2026-07-20",
      registrationDeadline: "2026-06-10",
    },
    format: "online",
    location: "",
    description: "Месячная онлайн-школа с итоговой защитой проектов.",
    website: "https://example.org/project-school",
    contactEmail: "school@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-4"),
    status: "draft",
    participantsCount: 0,
    customFields: [],
    createdAt: "2026-03-12T14:00:00.000Z",
  },
  {
    id: "evt-5",
    organizerId: "organizer-demo",
    title: "Школьный турнир по робототехнике",
    type: "other",
    level: "school",
    dates: {
      start: "2026-05-30",
      end: "2026-05-30",
      registrationDeadline: "2026-05-22",
    },
    format: "offline",
    location: "Екатеринбург",
    description: "Соревнование школьных команд по робототехнике.",
    website: "https://example.org/robot-school",
    contactEmail: "robot@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-5"),
    status: "published",
    participantsCount: 96,
    customFields: [],
    createdAt: "2026-03-07T11:20:00.000Z",
  },
  {
    id: "evt-6",
    organizerId: "organizer-demo",
    title: "Волонтерский интенсив",
    type: "volunteering",
    level: "regional",
    dates: {
      start: "2026-04-12",
      end: "2026-04-14",
      registrationDeadline: "2026-04-08",
    },
    format: "hybrid",
    location: "Нижний Новгород",
    description: "Практический интенсив по социальным проектам.",
    website: "https://example.org/volunteer",
    contactEmail: "volunteer@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-6"),
    status: "completed",
    participantsCount: 112,
    customFields: [],
    createdAt: "2026-01-18T12:00:00.000Z",
  },
  {
    id: "evt-7",
    organizerId: "organizer-partner",
    title: "Открытая олимпиада по математике",
    type: "olympiad",
    level: "national",
    dates: {
      start: "2026-09-10",
      end: "2026-09-12",
      registrationDeadline: "2026-09-01",
    },
    format: "online",
    location: "",
    description: "Олимпиада в онлайн-формате с прокторингом.",
    website: "https://example.org/math-open",
    contactEmail: "math@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-7"),
    status: "draft",
    participantsCount: 0,
    customFields: [],
    createdAt: "2026-03-18T09:00:00.000Z",
  },
  {
    id: "evt-8",
    organizerId: "organizer-partner",
    title: "Молодежный научный форум",
    type: "conference",
    level: "international",
    dates: {
      start: "2026-10-03",
      end: "2026-10-05",
      registrationDeadline: "2026-09-20",
    },
    format: "offline",
    location: "Новосибирск",
    description: "Форум исследовательских и инженерных проектов.",
    website: "https://example.org/forum",
    contactEmail: "forum@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-8"),
    status: "published",
    participantsCount: 210,
    customFields: [],
    createdAt: "2026-02-05T16:45:00.000Z",
  },
  {
    id: "evt-9",
    organizerId: "organizer-partner",
    title: "Digital Skills Bootcamp",
    type: "course",
    level: "university",
    dates: {
      start: "2026-07-05",
      end: "2026-08-05",
      registrationDeadline: "2026-06-25",
    },
    format: "online",
    location: "",
    description: "Интенсив по цифровым навыкам и карьерной подготовке.",
    website: "https://example.org/bootcamp",
    contactEmail: "bootcamp@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-9"),
    status: "published",
    participantsCount: 320,
    customFields: [],
    createdAt: "2026-01-22T13:30:00.000Z",
  },
  {
    id: "evt-10",
    organizerId: "organizer-partner",
    title: "Региональный хакатон по финтеху",
    type: "hackathon",
    level: "regional",
    dates: {
      start: "2026-08-19",
      end: "2026-08-21",
      registrationDeadline: "2026-08-10",
    },
    format: "hybrid",
    location: "Самара",
    description: "Хакатон по задачам финансовых сервисов.",
    website: "https://example.org/fintech",
    contactEmail: "fintech@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-10"),
    status: "published",
    participantsCount: 175,
    customFields: [],
    createdAt: "2026-02-28T15:00:00.000Z",
  },
  {
    id: "evt-11",
    organizerId: "organizer-partner",
    title: "Школьная конференция стартапов",
    type: "other",
    level: "school",
    dates: {
      start: "2026-11-12",
      end: "2026-11-12",
      registrationDeadline: "2026-11-01",
    },
    format: "offline",
    location: "Томск",
    description: "Питч-сессии школьных технологических стартапов.",
    website: "https://example.org/startup-school",
    contactEmail: "startup@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-11"),
    status: "cancelled",
    participantsCount: 0,
    customFields: [],
    createdAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "evt-12",
    organizerId: "organizer-partner",
    title: "Стажировочный волонтерский трек",
    type: "volunteering",
    level: "national",
    dates: {
      start: "2026-05-01",
      end: "2026-06-15",
      registrationDeadline: "2026-04-25",
    },
    format: "online",
    location: "",
    description: "Долгосрочная программа волонтерских проектов.",
    website: "https://example.org/vol-track",
    contactEmail: "track@example.org",
    logoUrl: "",
    bannerUrl: "",
    qrCodeUrl: buildEventQrCode("evt-12"),
    status: "completed",
    participantsCount: 284,
    customFields: [],
    createdAt: "2026-01-12T07:45:00.000Z",
  },
];

export function getMockEvents(): Event[] {
  return RAW_MOCK_EVENTS.map((event) => ({
    ...event,
    dates: { ...event.dates },
    customFields: event.customFields.map((field) => ({
      ...field,
      options: field.options ? [...field.options] : [],
    })),
  }));
}
